DROP TABLE IF EXISTS DIM_MOVIE;

CREATE TABLE IF NOT EXISTS DIM_MOVIE (
ID_MOVIE INT,
NAME VARCHAR,
MOVIE_GROUP VARCHAR,
RUNTIME INT,
RELEASE_YEAR INT,
INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO DIM_MOVIE (
ID_MOVIE, NAME, MOVIE_GROUP, RUNTIME, RELEASE_YEAR
)
VALUES (-1, 'unknown', 'unknown', -1, 1111);

INSERT INTO DIM_MOVIE (
SELECT 
    "Movie_ID" AS ID_MOVIE,
    "Movie_Title" AS NAME,
    CASE WHEN "Movie_Title" LIKE '%Part%' THEN REGEXP_REPLACE("Movie_Title", ' Part [12]','')
    ELSE "Movie_Title" END AS MOVIE_GROUP,
  	"Runtime" AS RUNTIME,
    "Release_Year" AS RELEASE_YEAR,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    "movie"
    )