DELETE FROM DIM_SPELL_LONG WHERE INCANTATION IN ('Unknown', 'unknown', 'pack', 'Pack', 'None', '') OR INCANTATION IS NULL;

DROP TABLE IF EXISTS DIM_SPELL;

CREATE TABLE IF NOT EXISTS DIM_SPELL (
    ID_SPELL INT,
    INCANTATION VARCHAR,
    SPELL_NAME VARCHAR,
    INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO DIM_SPELL (
    ID_SPELL, INCANTATION, SPELL_NAME
) VALUES (
    -1, 'unknown', 'unknown'
);

INSERT INTO DIM_SPELL (
    ID_SPELL, INCANTATION, SPELL_NAME, INSERTED_AT, UPDATED_AT
)
SELECT 
		ID_SPELL AS ID_SPELL,
		INCANTATION AS INCANTATION,
    SPELL_NAME AS SPELL_NAME,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    DIM_SPELL_LONG;