DROP TABLE IF EXISTS FACT_DIALOGUE;

CREATE TABLE IF NOT EXISTS FACT_DIALOGUE (
    ID_CHARACTER INT,
    ID_SCENE INT,
    ID_PLACE INT,
    ID_DIALOGUE INT,
    SENTIMENT_AFINN INT,
    SENTIMENT_NRC INT,
    DIALOGUE_LENGTH INT,
    LOVE_COUNT INT,
    INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
    );

INSERT INTO FACT_DIALOGUE (ID_CHARACTER, ID_SCENE, ID_PLACE, ID_DIALOGUE, SENTIMENT_AFINN, SENTIMENT_NRC, DIALOGUE_LENGTH,  LOVE_COUNT)
SELECT COALESCE(c.ID_CHARACTER,-1), 
        COALESCE(s.ID_SCENE,-1),
        COALESCE(p.ID_PLACE,-1),
        COALESCE(d."Dialogue_ID",-1),
        NULL AS SENTIMENT_AFINN,
        NULL AS SENTIMENT_NRC,
        ARRAY_SIZE(SPLIT(d."Dialogue", ' ')) AS DIALOGUE_LENGTH,
        REGEXP_COUNT(LOWER(d."Dialogue"), '(\\s|^)(love|loving|lover|loved|beloved)(\\s|$)') AS LOVE_COUNT

FROM DIALOGUE d
LEFT JOIN DIM_CHARACTER c ON d."Character_ID" = c.ID_CHARACTER
LEFT JOIN DIM_SCENE s ON d."Chapter_ID" = s.ID_SCENE
LEFT JOIN DIM_PLACE p ON d."Place_ID" = p.ID_PLACE
GROUP BY c.ID_CHARACTER, s.ID_SCENE, p.ID_PLACE, d."Dialogue_ID", ARRAY_SIZE(SPLIT(d."Dialogue", ' ')),REGEXP_COUNT(LOWER(d."Dialogue"), '(\\s|^)(love|loving|lover|loved|beloved)(\\s|$)');