DROP TABLE IF EXISTS DIM_HOUSE;

CREATE TABLE IF NOT EXISTS DIM_HOUSE (
ID_HOUSE INT,
HOUSE_NAME VARCHAR,
INSERTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO DIM_HOUSE (
ID_HOUSE, HOUSE_NAME
)
VALUES (-1, 'unknown');

INSERT INTO DIM_HOUSE (
SELECT 
    "House_ID" AS ID_HOUSE,
    "House_Name" AS HOUSE_NAME,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM
    "house"
    )